############################
#Accomplishes the following build tasks
#
#1) Runs the cloudformation template to create the necessary resources
#2) Runs python coverage function to generate Auto HTML documentation
##) Runs unit tests of lambda functions, checks aws resources created
#
#
############################
version: 0.2

phases:
  ###########################################
  #Uses a python runtime
  #Note that you do not need the \ to escape
  #aws cli commands
  ###########################################
  install:
    runtime-versions:
       python: 3.7
    commands:
      - echo Entered the install phase...

      - BUILD_ENVIRONMENT=prod
      - DESTINATION_BUCKET=dev-static-site-homepage
      - STATIC_WEBPAGE_STACK=dev-homepage-webpage
      - pip install -r tests/requirements.txt
      - ls -l
    finally:

  build:
    commands:
      - echo Defined build variables
      - echo $BUILD_ENVIRONMENT
      - echo $DESTINATION_BUCKET
      - echo $STATIC_WEBPAGE_STACK

      ###########################################
      #Copying web files from repo to s3 bucket
      ############################################
      - aws s3 cp ./web/home.html s3://ryanrigato.com/home.html

      ###########################################
      #Exclude and include parameters for sync are
      #evaluated against the source directory
      #The last filter applied takes precedence
      #--delete option deletes any files in the destination
      #that are not in the source
      ##########################################
      - aws s3 sync ./web s3://ryanrigato.com
        --exclude "*" --include "include/*" --delete

      - python tests/test_prod_aws_resources.py

      #merges dev branch into master now that all tests have
      #been passed and artifacts created
      - aws codecommit merge-branches-by-fast-forward
        --source-commit-specifier dev
        --destination-commit-specifier master
        --repository-name homepage

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - ./logs/*
