---
AWSTemplateFormatVersion: "2010-09-09"

#Transforms any serverless code to cloudformation
Transform: AWS::Serverless-2016-10-31

Description: |
  Lambda function that updates dynamodb table from
  templates/ratings_backend.yml

Parameters:
  BucketName:
    Type: String
    Default: source-code

  ProjectName:
    Type: String
    Default: ratings-update-lambda
Resources:

  WebsiteBucket:
    Properties:
      BucketName: !Join ['-', [ !Ref ProjectName, !Ref BucketName]]
    Type: "AWS::S3::Bucket"

############
#Lambda function to update ratings
#
############
  UpdateRatings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      CodeUri: s3://bucket/key
    Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: !Join ['', [ !Ref ProjectName, 'lambda-function']]
