---
AWSTemplateFormatVersion: "2010-09-09"

#Transforms any serverless code to cloudformation
Transform: AWS::Serverless-2016-10-31

Description: |
  Lambda function that updates dynamodb table from
  templates/ratings_backend.yml

Parameters:
  BucketName:
    Type: String
    Default: source-code

  DynamoDbTableName:
    Type: String
    Default: toonami_ratings

  ProjectName:
    Type: String
    Default: dev-ratings-backend


Resources:

  LambdaCodeBucket:
    Properties:
      BucketName: !Join ['-', [ !Ref ProjectName, !Ref BucketName ]]
      Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: !Join ['-', [ !Ref ProjectName, 'lambda-function']]
    Type: "AWS::S3::Bucket"

############
#Lambda function to update ratings
#
############
  UpdateRatings:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', [ !Ref ProjectName, 'lambda-poll']]
      Handler: index.handler
      Runtime: python3.7
      #Default code that will be updated by
      #CodeBuild Job
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
    Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: !Join ['-', [ !Ref ProjectName, 'lambda-function']]


###############################
#DynamoDb table to store ratings
#primary key is a composite of the
#show name and time
###############################
  RatingsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "RATINGS_OCCURRED_ON"
          AttributeType: "S"
        -
          AttributeName: "TIME"
          AttributeType: "S"

    #On demand dynamodb
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: "RATINGS_OCCURRED_ON"
          KeyType: "HASH"
        -
          AttributeName: "TIME"
          KeyType: "RANGE"

      SSESpecification:
          SSEEnabled: true
      TableName: !Ref DynamoDbTableName
      Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: !Join ['-', [ !Ref ProjectName, 'dynamodb']]
