---
AWSTemplateFormatVersion: "2010-09-09"

#Transforms any serverless code to cloudformation
Transform: AWS::Serverless-2016-10-31

Description: |
  Creates the backend storage and compute necessary for
  updating ratings

Parameters:
  ProjectName:
    Type: String
    Default: RatingsBackend

  RedditApiKey:
    Type: String
    Default: demokey

  RedditApiSecret:
    Type: String
    Default: demosecret

Resources:
######################
#VPC for  lambda function,
#and dynamodb table
######################
  RatingsVpc:
    Type: AWS::EC2::VPC
    Properties:
        CidrBlock: 192.168.0.0/20
        Tags:
          -
            Key: keep
            Value: "yes"
          -
            Key: reason
            Value: dynamo-private-vpc
          -
            Key: region
            Value: us-east-1
        #will show up as the name value in the vpc console
          -
            Key: Name
            Value: !Join ['', [!Ref ProjectName, '-vpc']]

######################
#Private subnet which will include lambda
#function
######################
  PrivateLambdaSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RatingsVpc
      CidrBlock: 192.168.0.0/24
      AvailabilityZone: !Select
        - 0
        - !GetAZs 'us-east-1'
      Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: lambda-private-subnet
        #will show up as the name value in the vpc console
        -
          Key: Name
          Value: !Join ['', ['private-subnet-', !Ref ProjectName]]

  BackendRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref RatingsVpc
      Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: Name
          Value: !Join ['', ['vpc-route-table', !Ref ProjectName]]

######################
#Private subnet association with main route table
#
######################
  # PrivateSubnetRouteAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     SubnetId: !Ref PrivateLambdaSubnet
  #     RouteTableId: !Ref BackendRouteTable


######################
#Reddit API key storage
#
######################
  RedditApiSecretsKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secrets string for reddit api key
      Name: /prod/reddit_api_key
      #SecretString: !Ref RedditApiKey
      Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: reddit-api-key

######################
#Reddit API key secret
#
######################
  RedditApiSecretsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secrets string for reddit api secret
      Name: /prod/reddit_api_secret
      Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: reddit-api-secret


###############################
#DynamoDb table to store ratings
#primary key is a composite of the
#show name and time
###############################
  RatingsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "RATINGS_OCCURRED_ON"
          AttributeType: "S"
        -
          AttributeName: "TIME"
          AttributeType: "S"

    #On demand dynamodb
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: "RATINGS_OCCURRED_ON"
          KeyType: "HASH"
        -
          AttributeName: "TIME"
          KeyType: "RANGE"

      SSESpecification:
          SSEEnabled: true
      TableName: "toonami_ratings"
      Tags:
        -
          Key: keep
          Value: "yes"
        -
          Key: reason
          Value: !Join ['', [ !Ref ProjectName, 'ratings-backend-dynamodb']]
