---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Creates a static website for hosting developer project documentation

Parameters:
  BucketName:
    Type: String
    Default: homepage
    Description: The name for the bucket hosting the static website

  NamePrefix:
    Type: String
    Default: dev-static-site
    Description: String for prefixing resources to differentiate prod/dev


  WebsiteDomainName:
    Type: String
    Default: "http://*.amazonaws.com"
    Description: |
        Necessary to allow Cross Origin Resource Sharing
        for JS to call html/css from the same domain




Resources:
  WebsiteBucket:

    Properties:
      BucketName: !Join
                    - '-'
                    #The second argument is a list
                    - - !Ref NamePrefix
                      - !Ref BucketName
      #########################
      #Used to determine cross origin
      #resource sharing rules for javascript
      #we only want to allow the s3 bucket and
      #eventually the domain name the site is registered
      #under to be able to upload images to this bucket
      ##########################
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            #HTTP methods allowed on bucket
            AllowedMethods:
              - "GET"
              - "POST"
            #allowed origin domain names
            AllowedOrigins:
              - !Ref WebsiteDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: "AWS::S3::Bucket"

  WebsiteBucketPolicy:
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
    Type: "AWS::S3::BucketPolicy"


# WebsiteCDNWithDomain:
#     Type: AWS::CloudFront::Distribution
#     Condition: HasDomainNameInfoCondition
#     Properties:
#       DistributionConfig:
#         Comment: CDN for S3-backed website
#         Aliases:
#           - !Join
#             - ''
#             - - !Ref 'AmazonConnectDomainName'
#         Enabled: 'true'
#         DefaultCacheBehavior:
#           ForwardedValues:
#             QueryString: 'true'
#           TargetOriginId: only-origin
#           ViewerProtocolPolicy: redirect-to-https
#         DefaultRootObject: index.html
#         Origins:
#           - CustomOriginConfig:
#               HTTPPort: '80'
#               HTTPSPort: '443'
#               OriginProtocolPolicy: http-only
#             DomainName: !GetAtt 'S3BucketForWebsiteContent.DomainName'
#             Id: only-origin
#         ViewerCertificate:
#           AcmCertificateArn: !Ref 'CertificateForCDN'
#           SslSupportMethod: sni-only
#         PriceClass: PriceClass_100


Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
