name: Updates web application
on:
  push:
    branches:
      - master

jobs:
  deploy-website-source-files:
    runs-on: ubuntu-latest
    name: web source files to s3
    defaults:
      run:
        working-directory: ./static
    steps:
      - name: checkout-current-branch
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run test

      - run: npm run build

      - name: assume-github-actions-role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{vars.REGION_NAME}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.PIPELINE_ROLE_NAME}}

      - name: script-execution-permissions
        run: chmod +x '../.github/scripts/homepage_source_files.sh'

      - name: upload-webpack-artifacts
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.PERSISTANT_STORAGE_ID}}
          AWS_DEFAULT_REGION: ${{vars.REGION_NAME}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PERSISTANT_STORAGE_KEY}}
        run: '../.github/scripts/homepage_source_files.sh'



  publish-commit-artifact:
    needs: deploy-website-source-files
    runs-on: ubuntu-latest
    name: favicon to s3 bucket
    env:
      ORCHESTRATION_SCRIPT: './.github/scripts/orchestrate_artifacts.sh'

    steps:
      - name: checkout-current-branch
        uses: actions/checkout@v3

      - name: script-execution-permissions
        run: chmod +x ${{env.ORCHESTRATION_SCRIPT}}

      - name: upload-favicon-artifacts
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.PERSISTANT_STORAGE_ID}}
          AWS_DEFAULT_OUTPUT: json
          AWS_DEFAULT_REGION: ${{vars.REGION_NAME}}
          AWS_S3_BUCKET_NAME: 'ryanrigato.com'
          AWS_SECRET_ACCESS_KEY: ${{secrets.PERSISTANT_STORAGE_KEY}}
        run: ${{env.ORCHESTRATION_SCRIPT}}


